services:
  db:
    image: postgres:15
    container_name: bera-beer-db
    restart: always
    environment:
      POSTGRES_USER: bera
      POSTGRES_PASSWORD: bera
      POSTGRES_DB: bera-beer
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: bera-beer-mqtt
    restart: always
    ports:
      - "1883:1883" # MQTT standard port
      - "9001:9001" # WebSocket port (se necessário)
    volumes:
      - ./apps/mqtt/config:/mosquitto/config
      - ./apps/mqtt/data:/mosquitto/data
      - ./apps/mqtt/log:/mosquitto/log
    environment:
      - MQTT_HOST=0.0.0.0
      - MQTT_PORT=1883

  redis:
    image: redis:alpine
    container_name: bera-beer-redis
    restart: always
    ports:
      - "6379:6379"

  bull-board:
    image: deadly0/bull-board
    container_name: bera-beer-bull-board
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUES=telemetry,operation
      - BULLMQ_MODE=true
      - REFRESH_INTERVAL=5000
      - MAX_JOBS_PER_PAGE=50
    ports:
      - "3020:3000"
    depends_on:
      - redis

  backend:
    build: ./apps/backend
    container_name: bera-beer-backend
    restart: always
    depends_on:
      - mqtt
      - redis
      - db
    environment:
      DATABASE_URL: postgres://bera:bera@db:5432/bera-beer
      MQTT_BROKER: mqtt://mqtt:1883
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ENV: dev
    ports:
      - "3000:3000"

  frontend:
    build: ./apps/frontend
    container_name: bera-beer-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_MQTT_BROKER=ws://mqtt:9001
    depends_on:
      - mqtt

volumes:
  db_data:
