services:
  db:
    image: postgres:15
    container_name: bera-beer-db
    restart: always
    environment:
      POSTGRES_USER: bera
      POSTGRES_PASSWORD: bera
      POSTGRES_DB: bera-beer
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: bera-beer-mqtt
    restart: always
    ports:
      - "1883:1883" # MQTT standard port
      - "9001:9001" # WebSocket port (se necessário)
    volumes:
      - ./apps/mqtt/config:/mosquitto/config
      - ./apps/mqtt/data:/mosquitto/data
      - ./apps/mqtt/log:/mosquitto/log
    environment:
      - MQTT_HOST=0.0.0.0
      - MQTT_PORT=1883

  kafka:
    image: bitnami/kafka:latest
    container_name: bera-beer-kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"

  backend:
    build: ./apps/backend
    container_name: bera-beer-backend
    restart: always
    depends_on:
      - mqtt
      - kafka
      - db
    environment:
      DATABASE_URL: postgres://bera:bera@db:5432/bera-beer
      MQTT_BROKER: mqtt://mqtt:1883
      KAFKA_BROKER: kafka:9092
      NODE_ENV: dev
    ports:
      - "3000:3000"

  frontend:
    build: ./apps/frontend
    container_name: bera-beer-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_MQTT_BROKER=ws://mqtt:9001
    depends_on:
      - mqtt

volumes:
  db_data:
